project_id = "ifoxciflbzczkzaczkkp"

[functions.generate-workout]
verify_jwt = false

[functions.progress-workout]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.analyze-body]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.musclewiki-media]
verify_jwt = false
